### ISSUE TITLE
Support for Middleman v4?

### ISSUE THREAD

**Issue by tomsabin** [middleman-contrib/middleman-deploy#93]
"Remove old module-style extension support" is on the list of the [v4 upgrade path](https://middlemanapp.com/basics/upgrade-v4/), which I believe has caused the following error when trying to rebuild a simple Middleman app:

```BASH
$ middleman build
.../gems/middleman-core-4.0.0.beta.2/lib/middleman-core/extensions.rb:96:in `load':
Tried to activate old-style extension: deploy. They are no longer supported. (RuntimeError)
```

```ruby
# config.rb
activate :deploy do |deploy|
  deploy.method = :git
end
```

Could anyone shed any light if there are any plans for v4 compatibility for middleman-deploy?

**Comment by rriemann** [comment]
There is a related pull-request #87 .

**Comment by fwolfst** [comment]
Do I understand correctly that we'll have to wait for 2.0 ? Currently I get the same error message as in the original post.

**Comment by danbartlett** [comment]
Using `gem 'middleman-deploy', '~> 2.0.0.pre.alpha'` as suggested in the referenced commit by @suzuryo worked for me

**Comment by kahboom** [comment]
Thanks @danbartlett; that workaround fixed it for me. 👍

**Comment by satanin** [comment]
HI @karlfreeman any change this (#87) will be merged into a non alpha version? 
Thx

**Comment by vaskaloidis** [comment]
Is anyone going to update the README ever? New Middleman users will have not be able to get it running without diagnosing two bugs and their solutions in two seperate Repo Issues: 1) The only working version requires people to use 2.0 pre-alpha despite the README saying 1.0, and 2) to use deploy_method in the config\, which has replaced method.. I would contribute, but the fix is sitting in an open pull-request for this!
